#BaseImage
FROM python:3.11-slim

#WorkDir
WORKDIR /app

#Copy
COPY requirements.txt .

#Install Dependencies
RUN pip install --no-cache-dir -r requirements.txt

#Copy project
COPY . .

#Expose
EXPOSE 8000

#Run FastAPI
CMD [ "uvicorn","main:app","--host","0.0.0.0","--port","8000" ]